#setwd("/home/ldapusers/dflouriot/Shiny/TDB_RubX/")
#getwd() 
#packrat::set_opts(external.packages = c("devtools"))
# unlink("./packrat/lib-R", recursive = TRUE)
# unlink("./packrat/lib-ext", recursive = TRUE)
library(devtools)
packrat::on()


#library(rmarkdown)
library(shiny)
library(shinyBS)
library(shinyjs)
library(shinydashboard)
library(shinythemes)
library(formattable)
library(dplyr)
library(DT)
library(datasets)
library(shinythemes)
#library(withr)
library(ggplot2)
library(plotly)
library(ggthemes)
library(stringr)
library(reshape2)
library(scales)
library(haven)
library(yaml)
library(readr)
library(crosstalk)
library(labeling)
# library(rJava)
# library(xlsxjars)
# library(xlsx)
library(plotrix)
library (dplyr)
library (RColorBrewer)

 
load(file = '/home/dflouriot/Documents/R/Scrapping/Cyclisme/Scrapping/Data/final_riders.RData')

.libPaths()
