#setwd("/home/dflouriot/Documents/R/Shiny_Cyclisme")
#getwd() 
#packrat::set_opts(external.packages = c("devtools"))
# unlink("./packrat/lib-R", recursive = TRUE)
# unlink("./packrat/lib-ext", recursive = TRUE)
#packrat::off()
library(devtools)
#library(shiny)
packrat::on()
#packrat::on()



#library(rmarkdown)
#library(shiny)
library(shinyBS)
library(shinyjs)
library(shinydashboard)
library(shinythemes)
#library(formattable)
library(dplyr)
library(DT)
library(datasets)
library(shinythemes)
#library(withr)
library(ggplot2)
library(plotly)
library(ggthemes)
#library(stringr)
library(reshape2)
library(scales)
library(haven)
library(yaml)
library(readr)
library(crosstalk)
library(labeling)
# library(rJava)
# library(xlsxjars)
# library(xlsx)
library(plotrix)
library (dplyr)
library (RColorBrewer)
library(sp)
library(rgdal)
library(leaflet)


lfile=list.files(path = "/home/dflouriot/Documents/R/Scrapping/Cyclisme/Scrapping/Data/CronData/", pattern = 'final_riders') 
load(file =paste0('/home/dflouriot/Documents/R/Scrapping/Cyclisme/Scrapping/Data/CronData/',lfile[max(length(lfile))]))

lfile_c=list.files(path = "/home/dflouriot/Documents/R/Scrapping/Cyclisme/Scrapping/Data/CronData/", pattern = 'team_country')
load(file =paste0('/home/dflouriot/Documents/R/Scrapping/Cyclisme/Scrapping/Data/CronData/',lfile_c[max(length(lfile_c))]))

load(file ='/home/dflouriot/Documents/R/Scrapping/Cyclisme/Scrapping/Data/CronData/results_agtop_races_classiques.RData')

map_countries=readOGR("/home/dflouriot/Documents/R/Shapes/Countries/World_Countries.shp")
